const COMMENT_MAX_CHAR = 120
const COLLECTION_MAX_CHAR = 30
const BIO_MAX_CHAR = 300
const CAPTION_MAX_CHAR = 2000

export const rules = {
  COMMENT_MAX_CHAR,
  COLLECTION_MAX_CHAR,
  BIO_MAX_CHAR,
  CAPTION_MAX_CHAR,
} as const
